# Generated by Django 4.0.3 on 2023-06-07 17:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_column='KorIme', max_length=20, primary_key=True, serialize=False, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(db_column='Sifra', max_length=128)),
                ('email', models.CharField(db_column='Email', max_length=40)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=10, null=True)),
                ('godiste', models.DecimalField(blank=True, db_column='Godiste', decimal_places=0, max_digits=4, null=True)),
                ('admin', models.IntegerField(db_column='Admin', default=0)),
                ('ime', models.CharField(blank=True, db_column='Ime', max_length=18, null=True)),
                ('prezime', models.CharField(blank=True, db_column='Prezime', max_length=18, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'korisnik',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('mesto', models.CharField(db_column='IDM', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mesto',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('ids', models.AutoField(db_column='IDS', primary_key=True, serialize=False)),
                ('slobodnitermini', models.CharField(blank=True, db_column='SlobodniTermini', max_length=1000, null=True)),
                ('cenovnik', models.CharField(blank=True, db_column='Cenovnik', max_length=1000, null=True)),
                ('adresa', models.CharField(blank=True, db_column='Adresa', max_length=18, null=True)),
                ('mesto', models.ForeignKey(blank=True, db_column='IDM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.mesto')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('idt', models.AutoField(db_column='IDT', primary_key=True, serialize=False)),
                ('maxclanova', models.IntegerField(blank=True, db_column='MaxClanova', null=True)),
                ('presektermina', models.CharField(blank=True, db_column='PresekTermina', max_length=1000, null=True)),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=50, null=True)),
                ('mesto', models.ForeignKey(blank=True, db_column='IDM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.mesto')),
            ],
            options={
                'db_table': 'tim',
            },
        ),
        migrations.CreateModel(
            name='Igrac',
            fields=[
                ('korisnik_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pozicija', models.IntegerField(blank=True, db_column='Pozicija', null=True)),
                ('termini', models.CharField(blank=True, db_column='Termini', max_length=1000, null=True)),
                ('brojdresa', models.IntegerField(blank=True, db_column='BrojDresa', null=True)),
            ],
            options={
                'db_table': 'igrac',
            },
            bases=('fudbal.korisnik',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RacunTima',
            fields=[
                ('idt', models.ForeignKey(db_column='IDT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fudbal.tim')),
                ('stanje', models.DecimalField(blank=True, db_column='Stanje', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'racun_tima',
            },
        ),
        migrations.CreateModel(
            name='Vlasnik',
            fields=[
                ('korisnik_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stanjeracuna', models.DecimalField(blank=True, db_column='StanjeRacuna', decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'vlasnik',
            },
            bases=('fudbal.korisnik',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TerminUtakmice',
            fields=[
                ('idtr', models.AutoField(db_column='IDTR', primary_key=True, serialize=False)),
                ('rezultat', models.CharField(blank=True, db_column='Rezultat', max_length=11, null=True)),
                ('cena', models.DecimalField(blank=True, db_column='Cena', decimal_places=4, max_digits=15, null=True)),
                ('placen', models.IntegerField(blank=True, db_column='Placen', null=True)),
                ('vreme', models.TimeField(blank=True, db_column='Vreme', null=True)),
                ('datum', models.DateTimeField(blank=True, db_column='Datum', null=True)),
                ('ids', models.ForeignKey(db_column='IDS', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.sala')),
                ('idt1', models.ForeignKey(db_column='IDT1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tim1', to='fudbal.tim')),
                ('idt2', models.ForeignKey(db_column='IDT2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tim2', to='fudbal.tim')),
            ],
            options={
                'db_table': 'termin_utakmice',
            },
        ),
        migrations.AddField(
            model_name='korisnik',
            name='mesto',
            field=models.ForeignKey(blank=True, db_column='IDM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.mesto'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='tim',
            name='idk_c_field',
            field=models.ForeignKey(db_column='Username', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='fudbal.igrac'),
        ),
        migrations.AddField(
            model_name='sala',
            name='idk',
            field=models.ForeignKey(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.vlasnik'),
        ),
        migrations.CreateModel(
            name='Pripada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uplata', models.DecimalField(blank=True, db_column='Uplata', decimal_places=2, max_digits=15, null=True)),
                ('idt', models.ForeignKey(db_column='IDT', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.tim')),
                ('idk', models.ForeignKey(db_column='Username', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='fudbal.igrac')),
            ],
            options={
                'db_table': 'pripada',
                'unique_together': {('idt', 'idk')},
            },
        ),
    ]
