# Generated by Django 4.0.3 on 2023-06-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pripada2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uplata', models.DecimalField(blank=True, db_column='Uplata', decimal_places=2, max_digits=15, null=True)),
                ('idk', models.ForeignKey(db_column='Username', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='fudbal.igrac')),
                ('idt', models.ForeignKey(db_column='IDT', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.tim')),
            ],
            options={
                'db_table': 'pripada2',
                'unique_together': {('idt', 'idk')},
            },
        ),
    ]
