# Generated by Django 4.0.3 on 2023-06-10 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0002_pripada2'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminutakmice',
            name='dan',
            field=models.CharField(blank=True, db_column='Dan', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('idp', models.AutoField(db_column='IDP', primary_key=True, serialize=False)),
                ('idk1', models.ForeignKey(db_column='IDK1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('idk2', models.ForeignKey(db_column='IDK2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tim2', to=settings.AUTH_USER_MODEL)),
                ('ids', models.ForeignKey(db_column='IDS', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.sala')),
            ],
            options={
                'db_table': 'poruke',
            },
        ),
    ]
