# Generated by Django 4.0.3 on 2023-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0003_terminutakmice_dan_poruke'),
    ]

    operations = [
        migrations.AddField(
            model_name='poruke',
            name='tip',
            field=models.IntegerField(db_column='tip', default=0),
        ),
    ]
