# Generated by Django 4.0.3 on 2023-06-10 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0004_poruke_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poruke',
            name='idk2',
            field=models.ForeignKey(db_column='IDK2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PorukeIgraca',
            fields=[
                ('idp', models.AutoField(db_column='IDP', primary_key=True, serialize=False)),
                ('tip', models.IntegerField(db_column='tip', default=0)),
                ('idi1', models.ForeignKey(db_column='IDI1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='igrac1', to='fudbal.igrac')),
                ('idi2', models.ForeignKey(db_column='IDI2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='igrac2', to='fudbal.igrac')),
            ],
            options={
                'db_table': 'poruke_igraca',
            },
        ),
    ]
