# Generated by Django 4.0.3 on 2023-06-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0006_porukeigraca_idt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porukeigraca',
            name='idt',
        ),
        migrations.AddField(
            model_name='porukeigraca',
            name='idt1',
            field=models.ForeignKey(db_column='IDT1', default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='timP1', to='fudbal.tim'),
        ),
        migrations.AddField(
            model_name='porukeigraca',
            name='idt2',
            field=models.ForeignKey(db_column='IDT2', default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='timP2', to='fudbal.tim'),
        ),
    ]
