# Generated by Django 4.0.3 on 2023-06-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0007_remove_porukeigraca_idt_porukeigraca_idt1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poruke',
            name='termin',
            field=models.CharField(blank=True, db_column='termin', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='porukeigraca',
            name='termin',
            field=models.CharField(blank=True, db_column='termin', max_length=4, null=True),
        ),
    ]
