# Generated by Django 4.0.3 on 2023-06-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0008_poruke_termin_porukeigraca_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poruke',
            name='termin',
            field=models.CharField(blank=True, db_column='termin', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='porukeigraca',
            name='termin',
            field=models.CharField(blank=True, db_column='termin', max_length=5, null=True),
        ),
    ]
