# Generated by Django 4.0.3 on 2023-06-17 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0010_poruke_idk3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrac',
            name='brojdresa',
            field=models.IntegerField(blank=True, db_column='BrojDresa', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='igrac',
            name='pozicija',
            field=models.IntegerField(blank=True, db_column='Pozicija', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='ime',
            field=models.CharField(blank=True, db_column='Ime', default='Korisnik', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='prezime',
            field=models.CharField(blank=True, db_column='Prezime', default='Bezimeni', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='terminutakmice',
            name='cena',
            field=models.DecimalField(blank=True, db_column='Cena', decimal_places=2, max_digits=15, null=True),
        ),
    ]
