# Generated by Django 4.0.3 on 2023-06-17 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0011_alter_igrac_brojdresa_alter_igrac_pozicija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrac',
            name='brojdresa',
            field=models.IntegerField(blank=True, db_column='BrojDresa', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='igrac',
            name='pozicija',
            field=models.IntegerField(blank=True, db_column='Pozicija', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
