# Generated by Django 4.0.3 on 2023-06-17 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0012_alter_igrac_brojdresa_alter_igrac_pozicija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrac',
            name='brojdresa',
            field=models.IntegerField(db_column='BrojDresa', default=13, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='igrac',
            name='pozicija',
            field=models.IntegerField(db_column='Pozicija', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='godiste',
            field=models.DecimalField(db_column='Godiste', decimal_places=0, default=2005, max_digits=4),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='ime',
            field=models.CharField(db_column='Ime', default='Korisnik', max_length=18),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='prezime',
            field=models.CharField(db_column='Prezime', default='Bezimeni', max_length=18),
        ),
    ]
