# Generated by Django 4.0.3 on 2023-06-17 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0013_alter_igrac_brojdresa_alter_igrac_pozicija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrac',
            name='brojdresa',
            field=models.IntegerField(db_column='BrojDresa', default=13, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='igrac',
            name='pozicija',
            field=models.IntegerField(db_column='Pozicija', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
