# Generated by Django 4.0.3 on 2023-06-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0014_alter_igrac_brojdresa_alter_igrac_pozicija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='mesto',
            field=models.ForeignKey(db_column='IDM', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fudbal.mesto'),
        ),
    ]
