# Generated by Django 4.0.3 on 2023-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0015_alter_korisnik_mesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(db_column='Email', max_length=40),
        ),
    ]
